"""Build Zensical and bundle the Rust API generated by rustdoc."""

import os
import shutil
import subprocess  # ruff: ignore[suspicious-subprocess-import] - fixed maintainer build commands.
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    """Build both references and copy the generated Rust HTML into the site."""
    subprocess.run(
        ["cargo", "doc", "--no-deps"],  # ruff: ignore[start-process-with-partial-path] - fixed build command.
        cwd=ROOT,
        env={**os.environ, "RUSTDOCFLAGS": "-D warnings"},
        check=True,
    )
    subprocess.run(["zensical", "build", "--clean"], cwd=ROOT, check=True)  # ruff: ignore[start-process-with-partial-path]
    shutil.copytree(ROOT / "target/doc", ROOT / "site/rust", dirs_exist_ok=True)


if __name__ == "__main__":
    main()
